version: '3'

services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ntr'
      MYSQL_USER: 'bmoroz'
      MYSQL_PASSWORD: 'hiperbalbinka'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
